### ISSUE TITLE
UrlJwkProvider crashes when pulling the same keys twice in a row

### ISSUE THREAD

**Issue by hanikesn** [auth0/jwks-rsa-java#109]
### Describe the problem

UrlJwkProvider crashes when pulling the same keys twice in a row. This problem only appeared after the recent Network Edge Migration. It seems the problem is related to the following line: https://github.com/auth0/jwks-rsa-java/blob/5d1e06c259769d7995dc67c1b2518894ec68a621/src/main/java/com/auth0/jwk/UrlJwkProvider.java#L124

Replacing it with
```java
var bytes = inputStream.readAllBytes();
return reader.readValue(bytes);
```
seems to fix the issue. My guess is that the existing connection isn't properly closed and Cloudflare doesn't seem to like that.

### Reproduction
```java
final var provider = new UrlJwkProvider("https://auth.rideos.ai/");
provider.getAll();
provider.getAll();
```

```
Exception in thread "main" com.auth0.jwk.NetworkException: Cannot obtain jwks from url https://auth.rideos.ai/.well-known/jwks.json
	at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:127)
	at com.auth0.jwk.UrlJwkProvider.getAll(UrlJwkProvider.java:133)
	at main(main.java:100)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://auth.rideos.ai/.well-known/jwks.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:123)
	... 2 more
```

### Environment

- **Version of this library used:** com.auth0:jwks-rsa:0.15.0
- **Version of Java used:** 11.0.1
- **Other modules/plugins/libraries that might be involved:** com.fasterxml.jackson:2.12.0
- **Any other relevant information you think would be useful:**

**Comment by jimmyjames** [comment]
Thank you for the detailed reproduction steps and stack trace! I do suspect there is something else going on related to the Network Edge migration that needs to be investigated first, before making changes to this SDK without understanding the specific cause and what the best solution may be (this SDK supports JDK 8 min, and `readAllBytes` was added in JDK 9, so if there is a change needed will need to likely find a JDK 8 compatible fix).

I'll keep this issue open for now, and if there's any updates on changes related to the Network Edge migration that has otherwise addressed this issue, please let us know.

**Comment by locomotif** [comment]
@jimmyjames - hope this message finds you well.  I wanted to follow up if there are any updates on this issue? Thank you!

**Comment by jimmyjames** [comment]
I wonder if using [toByteArray](https://guava.dev/releases/19.0/api/docs/com/google/common/io/ByteStreams.html#toByteArray(java.io.InputStream) from guava would work. I'm not able to reproduce this, but if someone has verified that using `readAllBytes` addresses this, and could see if using `toByteArray` would work, that seems like a change we could make.

```java
byte[] bytes = ByteStreams.toByteArray(inputStream);
return reader.readValue(bytes);
```

**Comment by jimmyjames** [comment]
@locomotif or @hanikesn, would either of you be willing to try using `toByteArray` from Guava as shown above, to see if it resolves the issue?

**Comment by jimmyjames** [comment]
If using a byte stream as input to the reader does resolve this issue, we would be happy to review a PR. We may need to evaluate any performance/stream size implications in that case, but that can be discussed in the context of any PR.
