### ISSUE TITLE
Discover JWKS URL from OIDC Configuration

### ISSUE THREAD

**Issue by davux** [auth0/jwks-rsa-java#112]
### Describe the problem you'd like to have solved

Automatic discovery of the JWKS URL following the [OIDC Configuration convention](https://auth0.com/docs/protocols/configure-applications-with-oidc-discovery).

### Describe the ideal solution

It would be nice if the library were able to receive the OIDC configuration URL as input, and fetch the key (with caching) automatically.

**Comment by jimmyjames** [comment]
Currently the JWKS URL is the configured domain + `/.well-known/jwks.json`. So to fetch a key with caching enabled:
```java
JwkProvider provider = new JwkProviderBuilder("https://samples.auth0.com/")
    .build();
Jwk jwk = provider.get("{kid of the signing key}");
```

Are you suggesting the ability to fetch the jwks URL from the OpenID configuration endpoint instead of using `./well-known/jwks.json` directly?

**Comment by davux** [comment]
Yes, exactly!

I understand that this library is for Auth0 and that Auth0 uses `.well-known/jwks.json`, so it's "good enough".

However, `jwks.json` it's not a [registered well-known entry](https://openid.net/specs/openid-connect-discovery-1_0.html), while `openid-configuration` is (through the [OIDC Discovery spec](https://openid.net/specs/openid-connect-discovery-1_0.html)). So at the bare minimum, the library should support the standard, as all Auth0 products normally do.

**Comment by jimmyjames** [comment]
Thanks for clarifying!

We're looking into what supporting the ability to pull the JWKS URI from the discovery endpoint might look like. It may not be something we tackle immediately, but In the meantime, you can of course create a `JwkProvider` from a `URL` to fetch the keys from. So something like:

```java
URL url = new URI("https://your-domain.auth0.com/.well-known/openid-configuration").normalize().toURL();

URLConnection connection = url.openConnection();
connection.setRequestProperty("Accept", "application/json");
ObjectReader reader = new ObjectMapper().readerFor(Map.class);

InputStream inputStream = connection.getInputStream();
byte[] bytes = ByteStreams.toByteArray(inputStream);
Map<String, Object> discoveryPayload = reader.readValue(bytes);
String jwksUri = (String) discoveryPayload.get("jwks_uri");

URL jwksUrl = new URI(jwksUri).normalize().toURL();
JwkProvider provider = new JwkProviderBuilder(jwksUrl)
        .build();

Jwk jwk = provider.get("kid");
```

**Comment by jimmyjames** [comment]
This isn't something we're going to change in the short-term, in terms of the default behavior (adding a second request to lookup the JWKS URI by default would add an additional network request). While we could provide a utility class to fetch the JWKS URL prior to constructing a `JwkProvider` via its `URL` constructor, that would just be a duplication of the code above that shows constructing the provider from the JWKS URL from the discovery endpoint above. And we wouldn't be able to reuse any of the networking configurations that the providers currently support. 

I'd recommend using the discovery URL directly prior to constructing the provider, as shown above. If we do ultimately support looking up from the discovery endpoint as part of this SDK, we'll want to make it opt-in and ensure we have consistency with our other JWKS SDKs, such as `node-jwks-rsa`.

**Comment by boev** [comment]
I am experiencing the same issue - basically there is a hardcoded (static final string) `.well-known/jwks.json` that gets added to whatever url one configures. In my opinion this is not good and should be made either configurable library property with a default of `.well-known/jwks.json` or offered to be configured in an additional constructor.

From what I can see this kind of issue is consistent among JWKS SDKs, so indeed a consistent fix would make sense. When the OAuth Server is outside of your control you cannot say where its public keys are located. Some do use URLs not ending with the hardcoded string and thus make this code harder to use.
