### ISSUE TITLE
com.auth0.jwk.SigningKeyNotFoundException: Cannot obtain jwks from url https://<oauth_server>/.well-known/jwks.json

### ISSUE THREAD

**Issue by jwtLearner** [auth0/jwks-rsa-java#12]
I am trying to validate incoming request that has authorization token (jwt) via Java JWT api. I was able to decode header and payload via that API but having trouble to validate the token. Little I know of this area, I thought I have to add jwks-rs-java api to my test project in order to handle validation part so I imported and ran following statements based on the documentation I read.

JwkProvider provider = new UrlJwkProvider("oauth_Server");
Jwk jwk = provider.get("keyId");

Then I got SingingKeyNotFoundException but caused by javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I am trying to understand the problem itself and how to rectify it. Did I provide wrong key id?  Do I need to import a certificate of the remote "oauth_server" into my local box in where I build/execute project in IDE?

I'd appreciate your advice and input on this matter. Thank you!

**Comment by ryber** [comment]
The method that takes a string is just used to find the domain and then builds a well known URI based on that. The resulting URI may or may not be valid. For example if you are using authorization servers in Okta your jwk_uri will actually be something like

"https://yourdomain.okta.com/oauth2/<auth server id>/v1/keys";

If you know (or can get) the exact proper URI you should use the constructor that takes a URI object

**Comment by lbalmaceda** [comment]
@jwtLearner You can either use the [URL](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/UrlJwkProvider.java#L28) or the [String](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/UrlJwkProvider.java#L39) variant of the `UrlJwkProvider` constructor (or any other Url Provider). If you use the first one, you'll have to input the full URL. But with the second one you just input the domain. Typically, the _jwks_ file is stored in the /.well-known/jwks.json path. (again, by using the URL constructor you can change that).

Similar to what @ryber said, to use it with Auth0 you'd pass your account's domain. Say I have an account called "mytenant" then the domain would be "mytenant.auth0.com" or "https://mytenant.auth0.com", either will do. By appending the well known path we form the https://mytenant.auth0.com/.well-known/jwks.json url. That's the file that it's downloaded/cached and checked when your provider seeks for a given "kid".
Cheers.

**Comment by cesartl** [comment]
I have a similar problem, though it used to work fine. The JwkProvider creates the right url (I can navigate to it without issue).

The issue seems to be with the SSL handshake:

```java
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
Any reason why my jdk wouldn't be able to find valid certificate to `*.eu.auth0.com`?

**Comment by lbalmaceda** [comment]
@cesartl Sounds weird, but definitely not a problem on the SDK itself. You mentioned you could access the URL just fine so it might have been a temporary issue with the backend. If the issue persists, please don't hesitate on dropping a message in https://support.auth0.com/

**Comment by pepper28** [comment]
I'm experiencing the same issue.  Does anyone know if this has been resolved or what one needs to do to correct it in the method.

**Comment by niklasravnsborg** [comment]
I also have the same issue!

**Comment by niklasravnsborg** [comment]
Quick fix: In my case the solution was to reinstall openjdk. I installed the newest version with brew on mac: `brew cask install adoptopenjdk13`.

**Comment by BoTime** [comment]
Have the same issue when using custom domain

**Comment by lbalmaceda** [comment]
@BoTime For this library, the concept of "custom domain" is not important. The provider class you instantiate must be given a valid URL to where the JWKS file is hosted.

**Comment by ryber** [comment]
I think it would be helpful for folks if the String constructor checked if the string was already configured with a .well-known and if it was just said "cool" and took it. I've had to explain this a few times internally at the company I work at and it seems to be a regular issue here.

**Comment by lbalmaceda** [comment]
@ryber we had this discussion with the team in the past and we agreed that the Javadoc of the class is self-explanatory. 

The URL provider has 2 constructor. One that accepts a "URL" instance (for you to create as you wish) and another that accepts a "Domain" string. So `Domain != "full URL"`

https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/UrlJwkProvider.java#L64-L69

**Comment by jinyanghuang** [comment]
I am using URL and defined the provider. I am getting this error when `provider.get(jwt.getKeyId())` `Cannot obtain jwks from url https://localhost:31300/.well-known/openid-configuration/jwks`. But I can access it through postman and get correct response.

**Comment by lbalmaceda** [comment]
@jinyanghuang I imagine the "https" in the URL could be making the certificate to be validated. Postman has a setting to disable the SSL verification, this library doesn't.

**Comment by OscarFB** [comment]
@lbalmaceda  Thanks, my problem is solved!!
//**********************************************************************
                        String jwks=***AQUI LA URL***
			URL url = new URL(jwks);
			JwkProvider provider = new UrlJwkProvider(url);
//*************************************************************************
