### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by EvanGertis** [auth0/jwks-rsa-java#125]
### Describe the problem
I am upgrading from JWKS RSA 0.6.1 to 0.7.0 and the build breaks.

### What was the expected behavior?
I should be able to run `mvn clean install` with version 0.9.0 and get the same results as if I ran `mvn clean install` with 0.6.1

### Reproduction

The issue shows up in legacy code.  That makes use of 

```
    <dependency>
      <groupId>com.auth0</groupId>
      <artifactId>java-jwt</artifactId>
      <version>3.15.0</version>
    </dependency>

    <dependency>
      <groupId>com.auth0</groupId>
      <artifactId>jwks-rsa</artifactId>
      <version>0.9.0</version>
    </dependency>
```

I was unable to reproduce the issue after creating a test project by following this guide https://www.toolsqa.com/java/maven/create-new-maven-project-eclipse/. I thought I could narrow the scope of the decencies to just these two and work out the issue, but it is possible other dependencies are contributing to this issue. I'd like to know if anyone else experienced breaking changes in their upgrade.

**Comment by EvanGertis** [comment]
This is correct.

**Comment by lbalmaceda** [comment]
I'll leave this open for another week in case someone came across the same issue and can help you pinpoint it. But as proved above, this library did not include breaking changes in the diff between those versions.

**Comment by jimmyjames** [comment]
Going to close this issue as we need more information to understand and verify that a breaking change was indeed introduced, and if so, what the potential cause would be. If you can provide more information, we'd be happy to reopen this issue and investigate. Thanks!
