### ISSUE TITLE
Base 64 decoder changed 

### ISSUE THREAD

**Issue by JoergAdler** [auth0/jwks-rsa-java#128]
### Describe the problem
In version 0.17.1 the implementation of Base64 decoding was changed from apache commons codec to the java build in one.

See for example here:
https://github.com/auth0/jwks-rsa-java/blob/ec5b25c91eaa9a01fcbfc98812089e2b5c8cac7a/src/main/java/com/auth0/jwk/Jwk.java#L185

The problem is, that this also changed from the **not url safe** implementation of apache commons codec to the url safe variant of jdk. Which breaks existing code.

### What was the expected behavior?

The implementation now is the correct one, as spec clearly says that the data in the jwk has to be base64 url encoded. I just wonder if there is a possibility to add compatibility code into e.g. https://github.com/auth0/jwks-rsa-java/blob/32f2a0410aceb88ab484aaa6b9576d935ba15ee0/src/main/java/com/auth0/jwk/Jwk.java#L232 

like suggested here: https://stackoverflow.com/a/26354677 (just doing a string replace)

That would not break existing code and would give users a chance to fix their jwk implementation, as the code would accept both url encoded and not encoded JSONs. The compatibility code can then be removed in a breaking release version like 1.0.0

### Reproduction
* Create a JWK with normal Base64 encoded exponent
* JWK will work in version 0.17.0
* JWK will not work for version 0.17.1 onwards 

### Environment
- **Version of this library used:**: 0.18.0
- **Version of Java used:**11

**Comment by skjolber** [comment]
@lbalmaceda  @jimmyjames was it intentional to switch from non-url-safe to url-safe? The JWKs from our Auth0 tenants are still regular base-64, but if that changes, we're going to have a problem.

**Comment by JoergAdler** [comment]
Ok. Thanks for clarification @skjolber. I was missing the part, that commons codec decoder is accepting both codecs for decoding. 

So migration path would be: stay at version 0.17.0, make sure all jwks are fulfilling the base64 url encoding. If not, switch the encoding of the jwk, as the library will accept both and then update to version 0.18.0
