### ISSUE TITLE
'key_ops' attempts to parse as a String rather than a List

### ISSUE THREAD

**Issue by chadramsey** [auth0/jwks-rsa-java#14]
Based on this specification (https://tools.ietf.org/html/rfc7517#page-7), 'key_ops' is expected to contain an array of values. Currently the 'key_ops' value is attempting to parse as a String, causing a ClassCastException to be thrown:

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String

This issue has been addressed in pull request #13

**Comment by lbalmaceda** [comment]
Closed on https://github.com/auth0/jwks-rsa-java/pull/13. Thanks for the contribution 🎉
