### ISSUE TITLE
com.auth0.jwk.NetworkException: Cannot obtain jwks from url

### ISSUE THREAD

**Issue by sivaraman-27** [auth0/jwks-rsa-java#163]
Hello, I'm encountering the issue "com.auth0.jwk.NetworkException: Cannot obtain jwks from url"

I'm trying to get the jwks from microsoft. But encountering the below issue
```
com.auth0.jwk.NetworkException: Cannot obtain jwks from url https://login.microsoftonline.com/common/discovery/v2.0/keys
        at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:139) ~[jwks-rsa-0.21.2.jar:0.21.2]
        at com.auth0.jwk.UrlJwkProvider.getAll(UrlJwkProvider.java:145) ~[jwks-rsa-0.21.2.jar:0.21.2]
        at com.auth0.jwk.UrlJwkProvider.get(UrlJwkProvider.java:163) ~[jwks-rsa-0.21.2.jar:0.21.2]
```

### What was the expected behavior?
Successfully obtain jwks from the specified url

### Reproduction

--

### Environment

- **Version of this library used:0.21.2**
- **Version of Java used:14**
- **Other modules/plugins/libraries that might be involved:--**
- **Any other relevant information you think would be useful:--**

**Comment by sivaraman-27** [comment]
**Update 1:**

I found the exception was thrown from 'UrlJwkProvider.java'. Below is the code

```
    private Map<String, Object> getJwks() throws SigningKeyNotFoundException {
        try {
            final URLConnection c = (proxy == null) ? this.url.openConnection() : this.url.openConnection(proxy);
            if (connectTimeout != null) {
                c.setConnectTimeout(connectTimeout);
            }
            if (readTimeout != null) {
                c.setReadTimeout(readTimeout);
            }

            for (Map.Entry<String, String> entry : headers.entrySet()) {
                c.setRequestProperty(entry.getKey(), entry.getValue());
            }

            try (InputStream inputStream = c.getInputStream()) {
                return reader.readValue(inputStream);
            }
        } catch (IOException e) {
            throw new NetworkException("Cannot obtain jwks from url " + url.toString(), e);
        }
    }
```

For new UrlJwkProvider, I'm only passing "Microsoft URL" alone, rest of them are null

```
    public UrlJwkProvider(URL url) {
        this(url, null, null, null, null);
    }

```

**Comment by sivaraman-27** [comment]
Hi, @jimmyjames. Can you give any reasons for the above error?

**Comment by shibukawa** [comment]
@axis80 I tested on AzureAD has the following OpenID configuration path

* `https://login.microsoftonline.com/<tenantID>/.well-known/openid-configuration`

And it returns the following path.

* `https://login.microsoftonline.com/common/discovery/keys`

I couldn't access the path you mentioned.

**Comment by jimmyjames** [comment]
Thanks everyone for the help and ideas!

I'm trying to understand the issue at hand here, if I try the following it works as expected:

```java
String url = "https://login.microsoftonline.com/common/discovery/v2.0/keys";

UrlJwkProvider provider = new UrlJwkProvider(new URI(url).normalize().toURL());
System.out.println(provider.get("{SOME-KID"));
```
 
@axis80 is correct that we don't currently traverse the discovery URL as discussed in #112, but not sure if that's related to this specific issue or not.

If there's an example that reproduces an issue let us know, thanks!

**Comment by jimmyjames** [comment]
Potentially related, #165 may help in this case by at least throwing a more specific exception.
