### ISSUE TITLE
NetworkException not being thrown when using cached JwkProviderBuilder instead of directly UrlJwkProvider

### ISSUE THREAD

**Issue by adFrej** [auth0/jwks-rsa-java#165]
### Describe the problem

As per: [examples](https://github.com/auth0/jwks-rsa-java/blob/master/EXAMPLES.md) we should be able to catch NetworkException when getting JWK using cached JwkProviderBuilder. But in [here](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/GuavaCachedJwkProvider.java) that error is caught and replaced with SigningKeyNotFoundException (as ExecutionException includes NetworkException):
```
@Override
public Jwk get(final String keyId) throws JwkException {
    try {
        String cacheKey = keyId == null ? NULL_KID_KEY : keyId;
        return cache.get(cacheKey, new Callable<Jwk>() {
            @Override
            public Jwk call() throws Exception {
                return provider.get(keyId);
            }
        });
    } catch (ExecutionException e) {
        throw new SigningKeyNotFoundException("Failed to get key with kid " + keyId, e);
    }
}
```
This basically recreates the issue: #79.

### What was the expected behavior?

NetworkException being thrown directly from: `JwkProviderBuilder(URL(...)).cached(...).build().get(...)` method when unable to connect to the url.

### Reproduction

- Create cached provider for some urlPath of an offline server: `val provider = JwkProviderBuilder(URL(urlPath)).cached(10, 1, TimeUnit.MINUTES).build()`
- Try to access the JWK for some keyId: `provider.get(keyId)`
- Get the SigningKeyNotFoundException: `Failed to get key with kid ****`
- Only able to trace exception.cause: `java.util.concurrent.ExecutionException: com.auth0.jwk.NetworkException: Cannot obtain jwks from url ****`

### Environment

- **Version of this library used:** 0.21.2
- **Version of Java used:** 11 (Kotlin 1.3.72)
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by jimmyjames** [comment]
Thanks @adFrej, we will look into this this week.

**Comment by jimmyjames** [comment]
We should be able to just unwrap the `ExecutionException` in the `GuavaCachedJwkProvider`:

```java
@Override
public Jwk get(final String keyId) throws JwkException {
    try {
        String cacheKey = keyId == null ? NULL_KID_KEY : keyId;
        return cache.get(cacheKey, () -> provider.get(keyId));
    } catch (ExecutionException e) {
        if (e.getCause() instanceof JwkException) {
            throw (JwkException) e.getCause();
        }
        throw new JwkException("Unable to obtain key with kid " + keyId, e);
    }
}
```

I'll get a PR up shortly.

**Comment by jimmyjames** [comment]
#169 should fix this 👍
