### ISSUE TITLE
Allow URL request without well-know suffix

### ISSUE THREAD

**Issue by rivaldorodrigues** [auth0/jwks-rsa-java#190]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwks-rsa-java#readme) and [Examples](https://github.com/auth0/jwks-rsa-java/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0/jwks-rsa/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwks-rsa-java/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When creating a `JWKProvider`, it is necessary to enter the base URL of the domain and the suffix `.well-known/jwks.json` will be added to this to form the final URL:  `https:{your-domain}/.well-known/jwks.json`

Therefore, it is not possible to make requests to URLs that do not follow this pattern (without the `.well-known/jwks.json` suffix) as is possible in the `node-jwks-rsa` library, as the builder will always add this suffix, meaning that, when performing the request, we receive a 404 error

### Describe the ideal solution

The `JKWProvider` could receive the full URL in the constructor, similarly to what happens in the NodeJs version.

To maintain compatibility, the `.well-known/jwks.json` suffix could be added by default after `.build()`.

```
// Request for https://samples.auth0.com/.well-known/jwks.json

JwkProvider provider = new JwkProviderBuilder("https://samples.auth0.com/")
    .build();
```

To use only the URL provided in the constructor, we could inform the builder using a method such as `withoutWellKnowJWKS()`, causing only the URL passed in the constructor to be considered.

```
// Request for https://samples.auth0.com/nondefault/

JwkProvider provider = new JwkProviderBuilder("https://samples.auth0.com/nondefault/")
    .withoutWellKnowJWKS()
    .build();
```

**Comment by jimmyjames** [comment]
👋 hi @rivaldorodrigues thanks for the issue and thoughtful implementation notes! I think this should be possible today using the `JwkProviderBuilder(URL url)` constructor:

```java
JwkProvider provider = new JwkProviderBuilder(new URL("https://samples.auth0.com/nondefault/"))
    .build();
```

That does not append the well-known suffix so I think it should meet your needs, let us know!
