### ISSUE TITLE
kid should be optional in key set

### ISSUE THREAD

**Issue by klease** [auth0/jwks-rsa-java#23]
According to section 4.5 in https://tools.ietf.org/html/rfc7517#section-4.4, the kid parameter is optional. Currently UrlJwkProvider throws a SigningKeyNotFoundException on get(null) when the set of keys contains a single key with no "kid" value.

**Comment by lbalmaceda** [comment]
@klease can I have your feedback on the PR please?

**Comment by lbalmaceda** [comment]
released on 0.6.0
