### ISSUE TITLE
com.auth0.jwk.Jwk.getPublicKey() returns null if not RSA

### ISSUE THREAD

**Issue by adrian-baker** [auth0/jwks-rsa-java#37]
The javadoc and the implementation of this method don't match, I expect a InvalidPublicKeyException if the key type is not RSA, but I instead get null:

    /**
     * Returns a {@link PublicKey} if the {@code 'alg'} is {@code 'RSA'}
     * @return a public key
     * @throws InvalidPublicKeyException if the key cannot be built or the key type is not RSA
     */
    @SuppressWarnings("WeakerAccess")
    public PublicKey getPublicKey() throws InvalidPublicKeyException {
        if (!PUBLIC_KEY_ALGORITHM.equalsIgnoreCase(type)) {
            return null;
        }

**Comment by lbalmaceda** [comment]
Thanks. I've added this to our backlog.
