### ISSUE TITLE
Dependency convergence errors when using alongside com.auth0:java-jwt:3.4.0

### ISSUE THREAD

**Issue by scooter72** [auth0/jwks-rsa-java#39]
Dependency convergence error for commons-codec:commons-codec:1.11 paths to dependency are:
+-myproject
  +-com.auth0:java-jwt:3.4.0
    +-commons-codec:commons-codec:1.11
and
+-myproject
  +-com.auth0:jwks-rsa:0.6.0
    +-commons-codec:commons-codec:1.9

Dependency convergence error for com.fasterxml.jackson.core:jackson-databind:2.9.6 paths to dependency are:
+-myproject
  +-com.auth0:java-jwt:3.4.0
    +-com.fasterxml.jackson.core:jackson-databind:2.9.6
and
+-myproject
  +-com.auth0:jwks-rsa:0.6.0
    +-com.fasterxml.jackson.core:jackson-databind:2.8.11.1

**Comment by lbalmaceda** [comment]
Since using `implementation` scope this should no longer be an issue. Anyway, everytime we make a new release we try to bump all the dependencies to their latests minors. I'll close this one but feel free to reopen if the issue persists on your side.
