### ISSUE TITLE
BucketImpl is not public

### ISSUE THREAD

**Issue by jmferland** [auth0/jwks-rsa-java#41]
BucketImpl is not public so I cannot use rate limiting without using `JwkProviderBuilder`. (Also I cannot set a connect and read timeout with `JwkProviderBuilder`, otherwise I would have just used it).

e.g. this is impossible:

`JwkProvider url = new UrlJwkProvider("https://samples.auth0.com/");`
`Bucket bucket = new Bucket(10, 1, TimeUnit.MINUTES);`
`JwkProvider provider = new RateLimitJwkProvider(url, bucket);`

**Comment by lbalmaceda** [comment]
That's right. You need to use the builder class. To achieve the snippet that you posted above you would do this:

```java
JwkProvider provider = new JwkProviderBuilder("https://samples.auth0.com/")
   .rateLimited(10, 1, TimeUnit.MINUTES)
   .build();
```

But if you want to specify a connect/read timeout (I think you forgot to demonstrate that on the snippet) you can't do it today. I'd add a method to the builder rather than changing the visibility of the bucket implementation. I'll leave this open to track it.

**Comment by jmferland** [comment]
Even better. Sounds great, thank you!

**Comment by apgv** [comment]
@brix4dayz:  You can do to this with UrlJwkProvider. Code copied from README:

`JwkProvider provider = new UrlJwkProvider(new URL("https://samples.auth0.com/"));`

**Comment by brix4dayz** [comment]
Unfortunately not, the `UrlJwkProvider` only looks for JWKS at `/.well-known/jwks.json` (which I think should customizable as well). We're not using Auth0 as our OIDC provider but we thought your lib's were the nicest to use.

As a result, it was easier to write a custom `JwkProvider` that used our Feign client to retrieve the JWKS. I opened this PR to get the conversation around adding custom provider support to the builder started: https://github.com/auth0/jwks-rsa-java/pull/47

**Comment by apgv** [comment]
That's not completely correct. Notice the new URL() passed as parameter to UrlJwkProvider. I have used this for the same reason as you with Keycloak as a provider which has a different URL to the jwks. As the README states : "Also it can load jwks.json file from any given Url (even to a local file in your filesystem)."

**Comment by brix4dayz** [comment]
Perfect! Thanks, that makes a lot more sense.
