### ISSUE TITLE
Provide a getPrivateKey method in Jwk

### ISSUE THREAD

**Issue by mjduijn** [auth0/jwks-rsa-java#53]
### Description

Signing JWT tokens will become easier if the `Jwk` class were to have a `createPrivateKey` method, similar to its [`getPublicKey`](https://github.com/auth0/jwks-rsa-java/blob/401880d5f7c08fb0a8891963b696a9d833430452/src/main/java/com/auth0/jwk/Jwk.java#L168) method.
The returned private key could be used in a [`KeyProvider`](https://github.com/auth0/java-jwt/blob/7fcd1bfece8197f0c44cd020a03045df6cf182de/lib/src/main/java/com/auth0/jwt/interfaces/KeyProvider.java#L27), which in turn can be used to create an algorithm with the capability to sign JWT tokens.

Like you already used for the public key, the [RFC](https://tools.ietf.org/html/rfc7518#section-6.3) states which parameters should be used for creating its private counterpart.
I would expect the method to raise an error if the jwk does not contain the correct parameters to create a private key.

### Prerequisites

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/jwks-rsa-java/issues) and [PRs](https://github.com/auth0/jwks-rsa-java/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of this library used: 0.7.0
- Version of Java used: 11
- Additional libraries that might be affecting your instance: -

**Comment by mjduijn** [comment]
You can create an `RSAPrivateKey` from a `JWK` with the following snippet:


    // For details of magic strings below see: https://tools.ietf.org/html/rfc7518#section-6.3
    try {
        Jwk jwk = jwkProvider.get(null); // get the first entry in the JwkProvider
        Map<String, Object> additionalAttributes = jwk.getAdditionalAttributes();
        KeyFactory kf = KeyFactory.getInstance("RSA");

        BigInteger modules = getValues(additionalAttributes, "n");
        BigInteger publicExponent = getValues(additionalAttributes, "e");
        BigInteger privateExponent = getValues(additionalAttributes, "d");
        BigInteger primeP = getValues(additionalAttributes, "p");
        BigInteger primeQ = getValues(additionalAttributes, "q");
        BigInteger primeExponentP = getValues(additionalAttributes, "dp");
        BigInteger primeExponentQ = getValues(additionalAttributes, "dq");
        BigInteger crtCoefficient = getValues(additionalAttributes, "qi");

        RSAPrivateKeySpec privateKeySpec = new RSAMultiPrimePrivateCrtKeySpec(
            modules,
            publicExponent,
            privateExponent,
            primeP,
            primeQ,
            primeExponentP,
            primeExponentQ,
            crtCoefficient,
            null
        );

        return (RSAPrivateKey) kf.generatePrivate(privateKeySpec);

    } catch (JwkException e) {
        // The only way to get here is if jwkProvider.get(null) throws an exception, i.e. there are no JWKs in the provider.
        // At this point we (in my company) have already verified that this is not the case.
        throw new RuntimeException("Unreachable");
    } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
        throw new RuntimeException(e);
    }

Note that the JWK (and thus JSON object) necessary for creating a private key contains additional keys compared to the public variant.
Hope this helps, feedback is more than welcome.

**Comment by Neeraj-Natu** [comment]
Hi guys, I have opened a pull request implementing the getPrivateKey method.
Maintainers please havea  look.

**Comment by lbalmaceda** [comment]
@mjduijn @Neeraj-Natu I assume the JWKS resource is hosted privately or how would you expect to keep external people away from the Private Key?

**Comment by mjduijn** [comment]
@lbalmaceda it could be mounted as a file, for instance from a kubernetes secret. Not sure I would go with hosting a jwk with private key information, even in a private network.

**Comment by Neeraj-Natu** [comment]
@mjduijn, @lbalmaceda  The jwks file that has private key should be hosted as a file within a Vault, (hashicorp Vault seems to be a good place for it). This file won't be exposed publicly for any users.
Although I would actually leave this question with the users of the library and provide the option rather making the decision on behalf of them.

**Comment by lbalmaceda** [comment]
We at Auth0 show how to use these types of libraries to load a Public RSA key for verifying ID tokens' signatures. The only concern I have is that even with guidance, devs could start publishing their own JWKS files with not just the Public Key but also the Private Key, not aware of the consequences of leaking such secrets. I understand that your use case is for a private, local or secure vault source. But still... the possibility of misusing this increases if we merge a feature like this. 
Let me consult this feature with the rest of the team.

**Comment by lbalmaceda** [comment]
Apologies for the delay. We decided to not move forward with this request, as it's not something we plan to support in the short/mid-term. We will focus this SDK on Auth0 use cases for now.
