### ISSUE TITLE
Version 0.8.0 not available in Maven Central

### ISSUE THREAD

**Issue by golszewski86** [auth0/jwks-rsa-java#56]
Version 0.8.0 has been released on Mar 28th but the latest version available in Maven Central is still 0.7.0: https://search.maven.org/search?q=g:%20com.auth0%20a:jwks-rsa

Please release version 0.8.0 to Maven Central

**Comment by lbalmaceda** [comment]
@golszewski86 I just did. Thanks for raising this `Last Synced: Wed Apr 03 14:12:45 GMT 2019`
