### ISSUE TITLE
Send HTTP_ACCEPT as application/json

### ISSUE THREAD

**Issue by zeonglow** [auth0/jwks-rsa-java#57]
### Description

When attempting to fetch the JWKS from a new server the following is set in the Accept Header
'HTTP_ACCEPT: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2'

This is the standard Java HTTP library behaviour.  

However Django Rest Framework will return it's API browser page if HTML is mentioned in the ACCEPT field, which obviously cannot be parsed as JSON.

I have included a small patch below, which should fix this,   you can use the 'git apply-patch' to recreate my commit.

```
From b71c07db38ab983b3ab9e072145db1c5e589a3be Mon Sep 17 00:00:00 2001
From: Chris Huang-Leaver <chrishl@ekit-inc.com>
Date: Mon, 15 Apr 2019 11:20:28 +1000
Subject: [PATCH] Explicitly set Accept parameter to request only JSON from
 server

Django REST Framework in particular returns HTML if 'text/html' is present in the 'Accept' field,  (it defaults to JSON if Accept is missing)

Explicitly setting Accept to 'application/json' ensures the correct behavior,  as content other than JSON will cause the key extraction process to fail.
---
 src/main/java/com/auth0/jwk/UrlJwkProvider.java | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/main/java/com/auth0/jwk/UrlJwkProvider.java b/src/main/java/com/auth0/jwk/UrlJwkProvider.java
index 790ffe1..f6fc9fc 100644
--- a/src/main/java/com/auth0/jwk/UrlJwkProvider.java
+++ b/src/main/java/com/auth0/jwk/UrlJwkProvider.java
@@ -96,6 +96,7 @@ public class UrlJwkProvider implements JwkProvider {
             if (readTimeout != null) {
                 c.setReadTimeout(readTimeout);
             }
+            c.setRequestProperty("Accept", "application/json");
             final InputStream inputStream = c.getInputStream();
             final JsonFactory factory = new JsonFactory();
             final JsonParser parser = factory.createParser(inputStream);
-- 
2.20.1
```

**Comment by lbalmaceda** [comment]
Hi @zeonglow. Thanks for pointing this out. Would you please open up a new PR with the diff? I can tell it's missing the tests for the introduced behavior. And I'd also like to extract those strings into private constants.
Cheers

**Comment by zeonglow** [comment]
I could, although I'm not sure when I will have time. It will be a lot
faster if you did.
Do I have permission to open pull requests on this repo?

**Comment by lbalmaceda** [comment]
Anyone can make PRs. You just need to fork the repo and after you're done with your changes, open a PR from your fork into this repo's remote. I've already opened a PR for you.
