### ISSUE TITLE
How to enable Http Proxy?

### ISSUE THREAD

**Issue by rajadilipkolli** [auth0/jwks-rsa-java#58]
We are deploying our code in openshift container and we are unable to communicate with auth0 provider as we need to connect to external world using proxy?

How to use proxy using java-rsa jar?

Related to #19

**Comment by lbalmaceda** [comment]
@rajadilipkolli Use of a proxy is still not supported in this library. For the time being you can use the code in that PR to enable it. I'll track this internally, though the priority will be dictated by product. I suggest you contact them directly at https://auth0.com/feedback.

**Comment by bric3** [comment]
Coming back almost year later, It would really be a nice addition to see proxy support.
