### ISSUE TITLE
optional 'alg'

### ISSUE THREAD

**Issue by jakubzloczewski** [auth0/jwks-rsa-java#6]
According to this spec: https://tools.ietf.org/html/rfc7517#section-4.4 'alg' jwks parameter is optional.

Now Jwk.fromValues will throw IllegalArgumentException when 'alg' is not present.

https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/Jwk.java#L69

**Comment by Deddiekoel** [comment]
I'm encountering this issue as well. Azure Active Directory omits the "alg" parameter and that results in a "com.auth0.jwk.SigningKeyNotFoundException: Failed to parse jwk from json" exception.

**Comment by brad-gorman** [comment]
It would be really good if this got merged in. I can't use this library because my JWKS does not set alg.

**Comment by chadramsey** [comment]
+1

**Comment by TheJeremyGray** [comment]
I'm having lots of issues around Azure Identity Management, including regular Azure AD tokens and Azure AD B2C tokens.  I was able to test https://github.com/auth0/jwks-rsa-java/pull/10 locally and it seemed to work.  Can we merge this?
