### ISSUE TITLE
UrlJwkProvider.get is hitting the internet on every call

### ISSUE THREAD

**Issue by glorat** [auth0/jwks-rsa-java#80]
### Description

UrlJwkProvider.get is hitting the internet on every call. I'd expect to hit at most once on construction to obtain the public keys once

### Reproduction

The original problem I was trying to solve was handling the case where auth0 was holding multiple public keys and they need to be matched to the JWT being verified. The obvious code to write would be like this

```scala
  val provider = new UrlJwkProvider(issuer)
  val decoded = JWT.decode(token)
    val keyId = decoded.getKeyId
    val keyInfo = provider.get(keyId)
    val publicKey = keyInfo.getPublicKey.asInstanceOf[RSAPublicKey]
    val algorithm = Algorithm.RSA256(publicKey, null)
    val verifier = JWT.require(algorithm)
      .withIssuer(issuer)
      .withAudience(audience)
      .build

    assertThrows[TokenExpiredException] {
      val jwt = verifier.verify(token)
    }
```
where we obtain only the right public key from the provider, which obtains it from the URL. However, the provider.get does an internet check on every call, which defeats the purpose of JWT verification being self-contained and fast
### Expectation
UrlJwkProvider instances should load public keys only once.

Also, it would be good to have an explicitly documented way of verifying a JWT subject to multiple keys - auth0 docs say this case should be accounted for but I find no code samples that do it well. My above may not be the preferred way. If so, I'll take alternative code

### Environment

> Please provide the following:
jwks-rsa-0.9.0
deps were
```
  "com.auth0" % "java-jwt" % "3.8.3",
  "com.auth0" % "jwks-rsa" % "0.9.0"
```

For reference, the dodgy code in question is in UrlJwkProvider
```java
    @Override
    public Jwk get(String keyId) throws JwkException {
        final List<Jwk> jwks = getAll();  // This calls getJwks, which then does the network hit
        if (keyId == null && jwks.size() == 1) {
            return jwks.get(0);
        }
```

p.s. I'm using scala for my testing but it is close enough to Java to understand

**Comment by glorat** [comment]
Note that if this were resolved as I suggest (only get on construction), this would also resolve this issue https://github.com/auth0/jwks-rsa-java/issues/79

**Comment by lbalmaceda** [comment]
The `UrlJwkProvider` class does nothing else than making a new request for each attempt of fetching a given key. If you want some cache in the middle, you must wrap the provider into a provider that handles cache. There are several providers listed on the readme. But I'd suggest you use the `JwkProviderBuilder` which has some good defaults. Check the snippet [here](https://github.com/auth0/jwks-rsa-java#jwkproviderbuilder).


Regarding the validation of the token claims, if you're already using `java-jwt` then it would be easier to plug this library into it by implementing a `KeyProvider` that makes use of the `JwkProvider` to fetch a given key id. See their readme for a [hint](https://github.com/auth0/java-jwt#using-a-keyprovider)

I hope it helps.
