### ISSUE TITLE
Support EC key type in JWK

### ISSUE THREAD

**Issue by wilddog1979** [auth0/jwks-rsa-java#87]
JWK entries can have type key types (kty) according to RFC 7517: RSA and EC. The current implementation is covering only RSA.

I'm working on a project where the token provider is signing JWT's with EC and those must be checked with JWKS which is containing the public keys of rotating EC .

I would like to make the Jwk class to work the way that it is recognising both key types and it is able to return the corresponding public keys according to the specified parameters in the JWK JSON entry.

**Comment by lbalmaceda** [comment]
We made this library with the intention to support Auth0 use cases. Auth0 currently only supports HS256 and RS256 signing algorithms, being RS256 the only one exposed in the JWKS endpoint. Adding support for EC in this library is a change we welcome, however not one we will invest time in doing it ourselves. If you'd like, feel free to send a PR and a member of our team will review it.
Thanks
